"""Schemas for products, product chat, and product planning."""

from __future__ import annotations

from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import model_validator
from sqlmodel import Field, SQLModel

from app.schemas.common import NonEmptyStr

RUNTIME_ANNOTATION_TYPES = (datetime, UUID)
ProductStatus = Literal["draft", "active", "archived"]
ProductOptimizeFor = Literal["balanced", "cheapest-acceptable", "highest-quality-within-budget"]
ProductMessageRole = Literal["user", "assistant", "system"]
ProductPlanStatus = Literal["draft", "approved"]
ProductPlannerMode = Literal[
    "auto", "fast-thinking", "deep-thinking", "security-planning", "custom"
]


class ProductExecutionPolicy(SQLModel):
    """Operator policy flags applied to approved execution."""

    requires_plan_approval: bool = True
    auto_start_on_approval: bool = True
    service_template: str = "standard"


class ProductBudgetPolicy(SQLModel):
    """Budget posture and advisory caps for a product."""

    daily_budget_cap_usd: float | None = None
    total_budget_cap_usd: float | None = None
    optimize_for: ProductOptimizeFor = "balanced"


class ProductPlannerPolicy(SQLModel):
    """Planner runtime preference for conversational product intake."""

    mode: ProductPlannerMode = "auto"
    model_override: str | None = None


class ProductBase(SQLModel):
    """Shared product fields."""

    name: NonEmptyStr
    slug: str | None = None
    description: str | None = None
    local_working_directory: str | None = None
    remote_repository_url: str | None = None
    status: ProductStatus = "draft"
    default_gateway_id: UUID | None = None
    execution_policy: ProductExecutionPolicy = Field(default_factory=ProductExecutionPolicy)
    budget_policy: ProductBudgetPolicy = Field(default_factory=ProductBudgetPolicy)
    planner_policy: ProductPlannerPolicy = Field(default_factory=ProductPlannerPolicy)

    @model_validator(mode="after")
    def _require_workspace_or_repo(self) -> "ProductBase":
        if not (self.local_working_directory or self.remote_repository_url):
            raise ValueError(
                "Provide at least a local working directory or a remote repository URL.",
            )
        return self


class ProductCreate(ProductBase):
    """Payload for creating a product."""


class ProductUpdate(SQLModel):
    """Payload for updating a product."""

    name: str | None = None
    slug: str | None = None
    description: str | None = None
    local_working_directory: str | None = None
    remote_repository_url: str | None = None
    status: ProductStatus | None = None
    default_gateway_id: UUID | None = None
    execution_policy: ProductExecutionPolicy | None = None
    budget_policy: ProductBudgetPolicy | None = None
    planner_policy: ProductPlannerPolicy | None = None


class ProductRead(SQLModel):
    """Read payload for a product."""

    id: UUID
    organization_id: UUID
    name: str
    slug: str
    description: str | None = None
    local_working_directory: str | None = None
    remote_repository_url: str | None = None
    status: ProductStatus
    default_gateway_id: UUID | None = None
    execution_policy: ProductExecutionPolicy = Field(default_factory=ProductExecutionPolicy)
    budget_policy: ProductBudgetPolicy = Field(default_factory=ProductBudgetPolicy)
    planner_policy: ProductPlannerPolicy = Field(default_factory=ProductPlannerPolicy)
    created_at: datetime
    updated_at: datetime


class ProductSummaryRead(ProductRead):
    """List-card payload for products."""

    services_count: int = 0
    active_services_count: int = 0
    latest_activity_at: datetime | None = None
    latest_plan_status: ProductPlanStatus | None = None
    estimated_total_budget_usd: float | None = None


class ProductMessageCreate(SQLModel):
    """Product chat input from the operator."""

    content: NonEmptyStr
    planner_mode_override: ProductPlannerMode | None = None
    planner_model_override: str | None = None


class ProductMessageRead(SQLModel):
    """Durable product chat message."""

    id: UUID
    product_id: UUID
    role: ProductMessageRole
    content: str
    meta: dict[str, object] | None = None
    created_at: datetime


class ProductServiceProposal(SQLModel):
    """Draft service generated by the planner."""

    name: str
    slug: str
    description: str | None = None
    objective: str | None = None
    epics: list[str] = Field(default_factory=list)


class ProductEpicProposal(SQLModel):
    """Initial epic draft generated by the planner."""

    title: str
    description: str | None = None
    priority: Literal["low", "medium", "high"] = "medium"
    service_slug: str | None = None


class ProductModelRecommendation(SQLModel):
    """Model choice proposed for one execution slice."""

    slice: str
    model_ref: str
    rationale: str
    estimated_cost_usd: float | None = None


class ProductPlanRead(SQLModel):
    """Current product plan payload."""

    id: UUID
    product_id: UUID
    status: ProductPlanStatus
    planner_agent_id: UUID | None = None
    planner_session_key: str | None = None
    planner_model_ref: str | None = None
    planner_status: str | None = None
    planner_status_reason: str | None = None
    planner_last_escalation_reason: str | None = None
    plan_sync_status: str | None = None
    plan_sync_error: str | None = None
    intake_summary: str | None = None
    objective: str | None = None
    target_audience: str | None = None
    scope: str | None = None
    exclusions: str | None = None
    missing_questions: list[str] = Field(default_factory=list)
    unresolved_question_keys: list[str] = Field(default_factory=list)
    completeness: dict[str, object] = Field(default_factory=dict)
    proposed_services: list[ProductServiceProposal] = Field(default_factory=list)
    initial_epics: list[ProductEpicProposal] = Field(default_factory=list)
    role_assignments: dict[str, object] = Field(default_factory=dict)
    model_recommendations: list[ProductModelRecommendation] = Field(default_factory=list)
    estimated_daily_budget_usd: float | None = None
    estimated_total_budget_usd: float | None = None
    budget_posture: str | None = None
    budget_warnings: list[str] = Field(default_factory=list)
    last_message_at: datetime | None = None
    approved_at: datetime | None = None
    created_at: datetime
    updated_at: datetime


class ProductPlanApproveRequest(SQLModel):
    """Approval request for starting service execution."""

    start_execution: bool = True
